name: Deploy Airflow DAG

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'
      - 'tests/**'
      - '.github/workflows/**'
      - 'docker-compose.yaml'
      - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        run: docker-compose up -d
          
      
      - name: Set permissions for Airflow logs directory
        run: |
             TODAY=$(date +%Y-%m-%d)
             sudo mkdir -p /opt/airflow/logs/scheduler/$TODAY && sudo chmod 777 /opt/airflow/logs/scheduler

      - name: Run unittests in Docker
        run: |
             docker exec airflow-server_airflow-webserver_1 whoami
             docker exec airflow-server_airflow-webserver_1 /bin/bash -c 'cd tests && pwd &&python -m unittest test_hello_world.py'
        
        # Adjust the above command based on how your Docker image is set up and how your tests are structured

      - name: Copy DAG to Airflow Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dags/"
          target: "/home/mira/airflow-server/dags"
