name: Deploy Airflow DAG

on:
  push:
    branches:
      - main
    paths:
      - 'dags/**'
      - 'tests/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v2
          with:
            python-version: '3.x' # Adjust this to your project's Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt # Adjust this command based on how you manage dependencies

      - name: Run tests
        run: pytest tests/

      - name: Copy DAG to Airflow Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dags/"
          target: "/home/mira/airflow-server/dags"
